### ISSUE TITLE
my-bookmark项目存在跨站脚本攻击漏洞

### ISSUE THREAD

**Issue by gh0stkey** [luchenqun/my-bookmark#10]
# 关于XSS
来自百度百科：
> XSS攻击全称跨站脚本攻击，是为不和层叠样式表(Cascading Style Sheets, CSS)的缩写混淆，故将跨站脚本攻击缩写为XSS，XSS是一种在web应用中的计算机安全漏洞，它允许恶意web用户将代码植入到提供给其它用户使用的页面中。

# 项目中的XSS

漏洞文件：https://github.com/luchenqun/my-bookmark/blob/master/routes/api.js#L1450
代码行数：1450

```html
<pre id="note" style="background-color:RGB(243,244,245); padding:0px 10px 0px 10px; margin:0px; width:60%; min-height:100%;display: inline-block;text-align: left; font-size: 15px; font-family:italic arial,sans-serif;word-wrap: break-word;white-space: pre-wrap;">\n\n${data}\n\n</pre>
```

在处理留言内容并且输出到页面中的时候直接将留言内容输出到了页面中，我这里评论了一段恶意的XSS的攻击代码`<svg/onload=alert(1)>`，其表示弹一个框并且内容为1。

测试案例：https://mybookmark.cn/api/notes/?shareNote=329

<img width="1679" alt="0" src="https://user-images.githubusercontent.com/24655118/57833067-c523fa00-77eb-11e9-897d-d5a4256fb2ae.png">

# 修复建议

建议在处理的时候使用HTML实体化编码的方式对留言内容进行编码然后再输出。

# 关于我

Vulkey_Chen,信息安全爱好者。
团队：米斯特安全团队
博客：gh0st.cn

**Comment by gh0stkey** [comment]
漏洞危害就是当A用户点开之后这个链接（我还没构建恶意代码，这是一个验证代码），我可以获取A用户的凭证，登录A用户的账号并操作ta的账号。

**Comment by luchenqun** [comment]
感谢你的提醒，已修复当前bug。
我主要是做C++后台开发的，这个书签系统是我为自己做的。后来想着独乐乐不如众乐乐，所以开源了。所以对web开发的一些安全经验不是很多。
再次感谢你。
