### ISSUE TITLE
有没有朋友弄个Docker镜像或者配置文件呢

### ISSUE THREAD

**Issue by ju0632** [luchenqun/my-bookmark#12]
有没有朋友弄个Docker镜像或者配置文件呢

**Comment by luchenqun** [comment]
这个我没怎么弄过docker，只能你自己去研究了。弄好了发个PR给我。

**Comment by luchenqun** [comment]
已完成Docker镜像。详情请见：https://hub.docker.com/repository/docker/luchenqun/mybookmark

**Comment by luchenqun** [comment]
@ju0632 已完成Docker镜像。详情请见：https://hub.docker.com/repository/docker/luchenqun/mybookmark
