### ISSUE TITLE
非常棒非常棒的extention

### ISSUE THREAD

**Issue by lifeike** [luchenqun/my-bookmark#13]
哥们你好, 无意间发现了您的这个extention,我觉得思路太牛逼了,开发者大多用vimium,但是正常的存储书签方式太图形化了,非常麻烦.您的这个就解决了这个问题.存入书签之后可以通过链接导航到书签页面,这是所有的书签extention做不到的.给你的思路点赞一万次.

不过这个也是稍微有点儿小bug,不知道是不是我使用的问题,首先没有找到同步chrome书签的选项,然后右键加入书签的时候,每次提示要重新登录,所以暂时还不能实际应用起来,但是思路真的很棒,我相信,这是vim化书签的最好解决方案,期待你的进一步开发.

再次点赞.

**Comment by luchenqun** [comment]
已经重新开发了一个书签插件，正在审核当中......
