### ISSUE TITLE
手机版chrome插件无法读取登录状态

### ISSUE THREAD

**Issue by squlenhat** [luchenqun/my-bookmark#15]
Yandex安卓浏览器安装chrome插件，通过插件操作书签添加，可正常弹出添加书签/备忘录的弹出窗，但不管实际是否已登录账号，均提示未登录的错误提示，之后跳转到登录界面，如实际已登录则再跳转到手机版主页（https://m.mybookmark.cn/#/tags） ，之后重复操作依旧无法添加书签

**Comment by luchenqun** [comment]
新版的插件，已经解决了此问题。不过还正在审核当中。。。
