### ISSUE TITLE
Invalid default value for 'icon'

### ISSUE THREAD

**Issue by NoverNobida** [luchenqun/my-bookmark#17]
I use MySQL 5.6.44, and when I inported schema.sql, I got the error message `Invalid default value for 'icon'`

**Comment by NoverNobida** [comment]
In `schema.sql`, **\`icon\` varchar(1024) DEFAULT NULL** should be **\`icon\` varchar(1024) DEFAULT NULL;**

**Comment by luchenqun** [comment]
thanks! already update!
