### ISSUE TITLE
请问能不能部署到宝塔面板上？

### ISSUE THREAD

**Issue by tableter** [luchenqun/my-bookmark#18]

**Comment by luchenqun** [comment]
肯定可以的。我记得有人写过一个教程你参考一下。
https://www.moerats.com/archives/943/

**Comment by tableter** [comment]
> 肯定可以的。我记得有人写过一个教程你参考一下。不过他的不是最新的版本哈。
> https://www.moerats.com/archives/943/

我已经装好了，感谢回复。
