### ISSUE TITLE
启动就报错

### ISSUE THREAD

**Issue by xiguafz** [luchenqun/my-bookmark#20]
pm2.json

{
  "apps": [{
    "name": "my-bookmark",
    "script": "adapter.js",
    "cwd": "/data/mystack/sites/mybookmark/src/config",
    "exec_mode": "fork",
    "max_memory_restart": "1G",
    "autorestart": true,
    "node_args": [],
    "args": [],
    "env": {
      
    }
  }]
}

Error: Cannot find module 'think-cache-file'

**Comment by luchenqun** [comment]
要执行 npm i 安装相应模块。
