### ISSUE TITLE
请问，可以添加一个，打开当前所有书签的功能吗？

### ISSUE THREAD

**Issue by coverthesea** [luchenqun/my-bookmark#28]
我平时也烦恼管理书签，试过很多开源软件，都不太适合。
看了下你这个功能，和我需要的比较贴近，然后只是我还有个小功能，就是当前这个文件夹分类下的标签，我需要能够同时打开到一个新的浏览器窗口中，请问，有这个计划吗？

![image](https://user-images.githubusercontent.com/48321555/126307268-61af191d-bdfa-4644-a102-8ed41765aa46.png)

比如在上面加按钮功能，点一下可以把当前这个分类下面的所有页面都打开

**Comment by luchenqun** [comment]
可以是可以，但是我觉得没必要。因为以后分类会比较多一次性打开很多会卡死浏览器。

**Comment by coverthesea** [comment]
> 可以是，但我觉得没必要。因为以后会比较多闲散会很多会卡死浏览器。

![image](https://user-images.githubusercontent.com/48321555/126426380-514e99e8-909b-4777-8493-932de0600c0a.png)


可能和使用习惯有关吧，你平时怎么使用这个的，我一般会使用全部打开功能，然后打开一堆标签页在那里等待查看，你一般只是用到哪个网页才去你这个书签网站找吗？
