### ISSUE TITLE
手机端有两个这样的bug

### ISSUE THREAD

**Issue by 332lfgb6** [luchenqun/my-bookmark#29]
1. 首页一直在转...
![image](https://user-images.githubusercontent.com/51245335/132522247-cbb089d8-dea0-4e4b-93a3-9b214152961d.png)
2. 让我必须选择分类，但是没有选择分类的按钮
![image](https://user-images.githubusercontent.com/51245335/132523149-138a6740-09ef-486d-8c78-4913834e6f4c.png)

**Comment by luchenqun** [comment]
修复了
