### ISSUE TITLE
作者可以考虑 导入OneTab格式书签的功能吗

### ISSUE THREAD

**Issue by TrickLin** [luchenqun/my-bookmark#32]
OneTab的导出文件就是一个txt 每行一个网址+网页标题
平时喜欢把看到过的内容全扔进进去OneTab 但内容多起来之后就开始卡
用到现在的结果是有十多个备份文件了 希望能找一个程序集中管理这些东西
如果能加入这个功能 就太方便了

**Comment by luchenqun** [comment]
不好意思哈，暂时没有此开发计划。因为此功能太小众了。
