### ISSUE TITLE
自建服务器，网页小图标依然通过favicon.lucq.fun解析

### ISSUE THREAD

**Issue by zc402** [luchenqun/my-bookmark#33]
在购买的云服务器中，通过docker安装，发现网址前面的小图标依然需要favicon.lucq.fun解析。如果开了代理连不上favicon.lucq.fun，所有图标就都是默认的小e。这是一个BUG吗？还是正常的设计？

总之很感谢你！我也是因为浏览器的书签同步功能老出错，才想要找个书签收藏网站。想说自己写个呢，github上搜索居然真的有

**Comment by luchenqun** [comment]
是的哦，小图标是有服务的。不是下载到你自己服务器的。。。

**Comment by zc402** [comment]
好的，谢谢解答！
