### ISSUE TITLE
目录只有一层？

### ISSUE THREAD

**Issue by YJL12345** [luchenqun/my-bookmark#34]
我的chrome书签有3层文件夹，导入后只剩下最外面的文件夹了，点开后这不乱了嘛，作者怎么解决的

**Comment by YJL12345** [comment]
而且书签多的不能用下拉式，只能一页页点击，太慢了

**Comment by YJL12345** [comment]
我希望用书签页面替换新标签页，这样我打开chrome就能用了，操作上模仿书签栏最好了，我一直找类似，没一个满意

**Comment by fulige18** [comment]
+1其他都好，就是导入后全部归到一级目录有点难受
