### ISSUE TITLE
建议：mysql以环境变量方式配置使用

### ISSUE THREAD

**Issue by banjuer** [luchenqun/my-bookmark#36]
docker把mysql一块打包，使用时没有指定挂载，那么下次更新app容器时，数据会不会丢失呢？建议定义数据目录，可挂载或者mysql以环境变量形式引入使用

**Comment by lxxself** [comment]
附议

**Comment by luchenqun** [comment]
会丢掉。在设置-->上传导出-->导出书签，你更新之后，再把它导入进去嘛。
或者，你直接进入docker容器里面，把MySQL数据导出来嘛。

**Comment by banjuer** [comment]
大致看了下代码，config.js中修改mysql相关参数从环境变量获取可信吗？抱歉哈，前端不太懂，如果有冒犯请海涵。

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by luchenqun** [comment]
@banjuer 数据库配置文件是这个哦 src/config/adapter.js
