### ISSUE TITLE
希望在新版中恢复原来的 按分类显示全部书签页面

### ISSUE THREAD

**Issue by James88** [luchenqun/my-bookmark#38]
看到有一个提交更新是“[首页只返回最近添加与最近点击](https://github.com/luchenqun/my-bookmark/commit/c8f183fbffcf5c751a37e210ebcc7532bebd0502)”
这个修改挺好的，很实用。

同时希望保留原有的 按书签分类 直接显示全部书签的页面 这样查找起来也很方便。谢谢。

**Comment by luchenqun** [comment]
现在有分类吧。
