### ISSUE TITLE
如何启用/禁用用户注册

### ISSUE THREAD

**Issue by DavideSOGG** [luchenqun/my-bookmark#40]
非常不错的项目 已经部署在了VPS上，不过作为自托管项目，仅靠robots.txt可能不能很好屏蔽某些访问。仅作为个人使用，如何在需要的情况下关闭注册或开启访问限制呢？

**Comment by luchenqun** [comment]
这个需要改一下后台代码了。你注册好之后，把相关注册账号删除即可。

**Comment by DavideSOGG** [comment]
申请加QQ群似乎没有回应。想问一下具体需要修改哪个JS呢？还有就是一个书签同时只能选择一个分类吗？一个书签似乎不能对应多个分类。

**Comment by luchenqun** [comment]
其实一开始就是能选择多个分类的。只是后面我觉得这个功能不合理，我就强制只能选择一个分类了。QQ群你可以再申请一下，一般我都会通过的。
